# Generated by Django 4.0.1 on 2022-01-29 04:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('vehicle_type', models.TextField()),
                ('plate_num', models.TextField()),
                ('max_capacity', models.IntegerField()),
                ('other_info', models.TextField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_driver', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.TextField(max_length=512, null=True)),
                ('arr_date_time', models.DateTimeField()),
                ('passengers_num', models.IntegerField()),
                ('vehicle_type', models.TextField(max_length=128, null=True)),
                ('other_request', models.TextField()),
                ('status', models.TextField(default='OPEN')),
                ('can_be_shared', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.driver')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Shared_info',
            fields=[
                ('shared_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('passengers_num', models.IntegerField()),
                ('is_valid', models.BooleanField(default=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.order')),
                ('sharer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideapp.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rideapp.myuser'),
        ),
    ]
